Logging to Excel file when an item is locked.
jamasoftware-ps/link_fixer pull request #3
Opened 2023-06-14 20:17 UTC by bmiller-jama

Logging to Excel file when an item is locked.

2023-06-16 13:59 UTC, bmiller-jama commented
@nmchale-jama I got the script to add multiple rows for one locked item and cleaned up the other things we discussed.  Let me know if you have any questions!

2023-06-21 17:48 UTC, nmchale-jama requested changes

2023-06-21 17:48 UTC, nmchale-jama commented on link_fixer.py
> +        item_lock_properties = (item.get('lock'))
remove outer parens

2023-06-21 17:48 UTC, nmchale-jama commented on link_fixer.py
> +    workbook.save("locked_items.xlsx")
Move save workbook to after post phase.

Check any failed patch response for the word locked in the reason.  and add to workbook.

2023-06-21 17:48 UTC, nmchale-jama commented on link_fixer.py
> +    workbook.save("locked_items.xlsx")
may need to add "item Name" to "broken_link_data" for access in post phase

2023-06-22 20:45 UTC, bmiller-jama commented
@nmchale-jama Made the changes we discussed on the Atari Link Fixer script: "Removed tuple for Excel headers, added functionality to check for locked items after script starts, and broken link map adjustments/logging for that."

2023-06-23 10:16 UTC, cmarqu commented on link_fixer.py
> +        logger.info("Item {} is locked and was added to the Excel workbook.")
```suggestion
        logger.info("Item {} is locked and was added to the Excel workbook.".format(item_name))
```

2023-06-26 17:52 UTC, trobinson-jama commented on link_fixer.py
> +                        print("Item was locked and has a broken link.  Logging to Excel File...\n")
Change to logger.warn statement

2023-06-26 17:52 UTC, trobinson-jama commented on link_fixer.py
> +                            print("Log locked items method successful for " + str(b.get('name')))
Change to logger.info statement

2023-06-26 17:55 UTC, trobinson-jama commented on requirements.txt
Change py rest client to 17.1

2023-06-26 21:27 UTC, trobinson-jama approved these changes

2023-06-26 21:28 UTC, merged